"""empty message

Revision ID: 3c4b62261659
Revises: 
Create Date: 2023-08-23 21:44:44.365714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4b62261659'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fighters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('ap', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('win_loss', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fighter1_id', sa.Integer(), nullable=False),
    sa.Column('fighter2_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fighter1_id'], ['fighters.id'], name=op.f('fk_matches_fighter1_id_fighters')),
    sa.ForeignKeyConstraint(['fighter2_id'], ['fighters.id'], name=op.f('fk_matches_fighter2_id_fighters')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_matches_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('users')
    op.drop_table('fighters')
    # ### end Alembic commands ###
