"""empty message

Revision ID: 45335087cbd9
Revises: 5217b8d63537
Create Date: 2023-08-28 00:09:28.926883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45335087cbd9'
down_revision = '5217b8d63537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fighters', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fighters', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
