"""empty message

Revision ID: 5217b8d63537
Revises: 2b43eaaa0a02
Create Date: 2023-08-27 23:52:22.729981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5217b8d63537'
down_revision = '2b43eaaa0a02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fighters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fighters', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
