"""empty message

Revision ID: 88799a3f5dec
Revises: dd30f1d54958
Create Date: 2023-08-28 16:44:52.924483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88799a3f5dec'
down_revision = 'dd30f1d54958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fighters', schema=None) as batch_op:
        batch_op.drop_column('image_cycle')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fighters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_cycle', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
