"""empty message

Revision ID: 9fc51f47edee
Revises: 45335087cbd9
Create Date: 2023-08-28 02:04:12.467995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc51f47edee'
down_revision = '45335087cbd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fighters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))
        batch_op.drop_column('icon')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fighters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.BLOB(), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###
