"""empty message

Revision ID: dd30f1d54958
Revises: 0b63e833f5ef
Create Date: 2023-08-28 16:43:51.100149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd30f1d54958'
down_revision = '0b63e833f5ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fighters', schema=None) as batch_op:
        batch_op.alter_column('image_cycle',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_column('sprite_loss')
        batch_op.drop_column('sprite_win')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fighters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sprite_win', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('sprite_loss', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('image_cycle',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
